spring:
  batch:
    job:
      enabled: false  # 애플리케이션 시작 시 자동으로 배치 실행하지 않음
    jdbc:
      initialize-schema: always  # 배치 메타데이터 테이블 자동 생성
  datasource:
    url: jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always  # SQL 스크립트 자동 실행
  h2:
    console:
      enabled: true  # H2 콘솔 활성화 (개발용)

aws:
  s3:
    bucketName: roobly-test
    region: ap-southeast-2
  credentials:
    accessKey: ${S3_ACCESS_KEY}
    secretKey: ${S3_SECRET_KEY}